export const scrollTop = state => state.scrollTop;
export const slide = state => state.slide;
export const recommend = state => state.recommend;
export const popularize = state => state.popularize;
export const online = state => state.online;
export const donghua = state => state.module[0];
export const bangumi = state => state.module[1];
export const guochuang = state => state.module[2];
export const module = state => state.module;
